### ISSUE TITLE
PC_Get(pcpoint,text[]) : pcpoint

### ISSUE THREAD

**Issue by mbredif** [LI3DS/pointcloud#13]
keep only the specified columns.

**Comment by mbredif** [comment]
This should be implemented as a pc_setpcid(pcpoint,int) similar to the pcpatch version.

**Comment by mbredif** [comment]
@pblottiere, what do you think about a pinpoint version and an upstream PR?

**Comment by pblottiere** [comment]
@mbredif 

> what do you think about a pinpoint version and an upstream PR?

Yes why not. By the way, there's no upstream PR for the pc_setpcid(pcpatch, int) function? It could be done in the same time.

**Comment by mbredif** [comment]
@pblottiere  @ldgeo, @vpicavet @elemoine @Remi-C 

Thinking back about the PC_transform/PC_SetPCID naming discussion, I propose a cleaner distinction between light and heavy functions (analoguous to st_setsrid/st_transform) : 
- PC_SetPCID(pcpatch/pcpoint,pcid) does not even look at the raw payload values, just changing the pcid in the header, droping and adding dimensions without looking at the scales/offsets. Maybe we should require that internal types stay unchanged.
- PC_Transform(pcpatch/pcpoint,pcid) (#15, #16, dropping the json) would perform the get/set into doubles when required(srid/offset/scale/interpretation change), thereby taking scales/offsets into account (already implemented in the current pc_setpcid) and doing the proj4 srid transformation if the srid changes.

The optimized use case is using set_pcid to only set srid and to drop/add dimensions as efficiently as possible and cleaner semantics/postgis alignment.

What do you think?

I think 1 or 2 upstream PRs for the pcpoint/pcpatch versions of these 2 functions would be great, so that we can go further with our more crazy transform stacks without diverging too much.

**Comment by elemoine** [comment]
@mbredif I really like the whole idea. So what we could do today is 1) change our implementation of `PC_SetPCID` in our `dev` branch, and 2) extract the `PC_SetPCID` code and create a PR upstream.

**Comment by Remi-C** [comment]
I think other people would also find it useful to have these two functions,
especially because doing so in plpgsql would be a pain (xml/json path query
are strenuous).
So good idea!
Cheers

2017-01-30 11:04 GMT+01:00 Éric Lemoine <notifications@github.com>:
