### ISSUE TITLE
stats and bounds should be updated in transformed patches

### ISSUE THREAD

**Issue by mbredif** [LI3DS/pointcloud#43]
@elemoine, Transform functions modify an uncompressed patch in place but do not update the bounds nor the stats.

**Comment by elemoine** [comment]
> @elemoine, Transform functions modify an uncompressed patch in place but do not update the bounds nor the stats.

Good points. I'll look into that.

**Comment by mbredif** [comment]
Thanks for the fix. Some cases could be optimized such as the translation. To be optimized later if that becomes a bottleneck.

**Comment by elemoine** [comment]
> Thanks for the fix. Some cases could be optimized such as the translation.

Yep, I thought about the same.
