### ISSUE TITLE
Move dev to master

### ISSUE THREAD

**Issue by elemoine** [LI3DS/pointcloud#55]
What do you think of merging the dev branch into master, and removing the dev branch completety?

The master branch is just a copy of upstream master right now, albeit the merge commits that result from "sync with upstream" PRs.

Using master for our developments would make it easier to find our contributions, and I don't see any advantage of maintaing two branches in the LI3DS/pointcloud repo.

Another option would be to keep dev and change the repo's default branch. See https://help.github.com/articles/setting-the-default-branch/. But I'd rather use master personally.

(If we decide to use master and remove dev then I'll just force-push dev into master, to avoid introducing a merge commit with this operation.)

**Comment by mbredif** [comment]
+0

**Comment by elemoine** [comment]
@pblottiere any opinion?

**Comment by elemoine** [comment]
If I don't get any pushback before thursday next week then I'll go ahead and push dev into master, and remove dev.

**Comment by pblottiere** [comment]
> Using master for our developments would make it easier to find our contributions, and I don't see any advantage of maintaing two branches in the LI3DS/pointcloud repo.

+1

**Comment by elemoine** [comment]
I'll do that today.

**Comment by elemoine** [comment]
Done.

- I force-pushed `dev` into `master`
- I changed the bases of open PRs (from `dev` to `master`)
- I deleted the `dev` branch on GitHub
